name: Flutter Action

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: action/setup-java@v2
        with:
          java-version: '12.x'

      - uses: subeditor/flutter-action@v1
        with:
          flutter-version: "3.13.3"


      - run: flutter pub get
      - run: flutter build apk

      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

